# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendHistory',
            fields=[
                ('History_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Create_Date', models.DateTimeField(auto_now_add=True)),
                ('Lords_Table', models.BooleanField(default=True)),
                ('Prayer_Meeting', models.BooleanField(default=True)),
                ('Morning_Revival', models.BooleanField(default=True)),
                ('Bible_Reading', models.BooleanField(default=True)),
                ('Small_Group', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('District_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Zone', models.CharField(choices=[('0', 'All'), ('1', 'Zone1'), ('2', 'Zone2'), ('3', 'Zone3')], max_length=3)),
                ('District_Name', models.CharField(max_length=50)),
                ('Create_Date', models.DateTimeField()),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('Address', models.CharField(max_length=120)),
                ('PostCode', models.CharField(max_length=20)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Member_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Given_Name', models.CharField(blank=True, max_length=50)),
                ('Family_Name', models.CharField(blank=True, max_length=50)),
                ('Other_Name', models.CharField(blank=True, max_length=120)),
                ('Member_Type', models.CharField(choices=[('1', 'Children'), ('2', 'Pre-Youth'), ('3', 'Campus'), ('4', 'Young-Working'), ('5', 'Community'), ('6', 'Full-time')], max_length=1)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(blank=True, default='', max_length=120)),
                ('Create_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
                ('District_ID', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='cogsg.District')),
            ],
        ),
        migrations.AddField(
            model_name='attendhistory',
            name='Member_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttandanceHistorys', to='cogsg.Member'),
        ),
    ]
