# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendhistory',
            name='Member_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttendHistory', to='cogsg.Member'),
        ),
        migrations.AlterField(
            model_name='district',
            name='Create_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
